# Generated by Django 5.1.8 on 2025-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('price_prediction', models.JSONField()),
                ('risk_level', models.CharField(max_length=20)),
                ('analysis_summary', models.TextField()),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
